Step 1 : Import Pandas Library

In [1]:
# Import the Pandas library for data manipulation and analysis
# The 'as pd' shortcut makes the code shorter and faster to type
import pandas as pd

Step 2 : Create DataSet

In [2]:
# Create a dictionary containing sample student records (ID, name, age, city, and marks)
# This raw dictionary will be used next to build a structured data table
data = {
    "Id" :[101,102,103,104,105,106,107],
    "Name":["rahul","priya","amit","riya","karan", "krisha","harry"],
    "age":[20,21,19,20,22,24,28],
    "city":["surat","navsari","bharuch","gandhinagar","surat","valsad","ahemedabad"],
    "marks":[85,92,70,80,81,84,90]
}

Step 3 : Create DataFrame

In [3]:
# Convert the dictionary into a Pandas DataFrame, which structures it like an Excel table
# Display the table to review the organized columns and rows of data
df =pd.DataFrame(data)
df

    Id    Name  age         city  marks
0  101   rahul   20        surat     85
1  102   priya   21      navsari     92
2  103    amit   19      bharuch     70
3  104    riya   20  gandhinagar     80
4  105   karan   22        surat     81
5  106  krisha   24       valsad     84
6  107   harry   28   ahemedabad     90

Step 4 : Save Data as CSV file

In [4]:
# Save the data inside the dataframe (df) into a new file named "students.csv"
# index=False prevents pandas from adding an extra column of row numbers
df.to_csv("students.csv",index=False)
# Print a friendly message to let you know the file was successfully saved
print("csv file create successfully.")

csv file create successfully.

Step 5 : Save Data as Excel file

In [5]:
# Save the data inside the dataframe (df) into an Excel file named "students.xlsx"
# index=False prevents pandas from saving row numbers as a separate column
df.to_excel("students.xlsx",index=False)
# Print a message to confirm the file has been saved successfully
print("Excel file create successfully.")

Excel file create successfully.

Step 6 : Save Data as JSON file

In [6]:
# Save the dataframe (df) as a JSON file named "students.json"
# orient="records" formats the data like a list of dictionaries (key-value pairs)
# indent=4 formats the file with nice spacing so it is clean and easy to read
df.to_json("students.json",orient="records",indent=4)
print("JSON file create successfully.")
# Print a message to confirm the file has been saved successfully

JSON file create successfully.

Step 7 : Read Data From CSV file

In [7]:
# Read the CSV file into a new DataFrame.
df_csv = pd.read_csv("students.csv")
# Display the data.
df_csv

    Id    Name  age         city  marks
0  101   rahul   20        surat     85
1  102   priya   21      navsari     92
2  103    amit   19      bharuch     70
3  104    riya   20  gandhinagar     80
4  105   karan   22        surat     81
5  106  krisha   24       valsad     84
6  107   harry   28   ahemedabad     90

Step 8 : Read Data From Excel file

In [8]:
# Read the Excel file into a new DataFrame.
df_excel = pd.read_excel("students.xlsx")
# Display the data.
df_excel

    Id    Name  age         city  marks
0  101   rahul   20        surat     85
1  102   priya   21      navsari     92
2  103    amit   19      bharuch     70
3  104    riya   20  gandhinagar     80
4  105   karan   22        surat     81
5  106  krisha   24       valsad     84
6  107   harry   28   ahemedabad     90

Step 9 : Read Data From JSON  file

In [9]:
# Read the JSON file into a new DataFrame.
df_json = pd.read_json("students.json")
# Display the data.
df_json

    Id    Name  age         city  marks
0  101   rahul   20        surat     85
1  102   priya   21      navsari     92
2  103    amit   19      bharuch     70
3  104    riya   20  gandhinagar     80
4  105   karan   22        surat     81
5  106  krisha   24       valsad     84
6  107   harry   28   ahemedabad     90

step 10 : Display first 5 record

In [10]:
# Display the first five rows of the DataFrame.
df_csv.head()

    Id   Name  age         city  marks
0  101  rahul   20        surat     85
1  102  priya   21      navsari     92
2  103   amit   19      bharuch     70
3  104   riya   20  gandhinagar     80
4  105  karan   22        surat     81

Step 11 : Display Last 5 Record

In [11]:
# Display the last five rows of the DataFrame.
df_csv.tail()

    Id    Name  age         city  marks
2  103    amit   19      bharuch     70
3  104    riya   20  gandhinagar     80
4  105   karan   22        surat     81
5  106  krisha   24       valsad     84
6  107   harry   28   ahemedabad     90

Step 12 : Display Information

In [12]:
# Display information about the DataFrame,
# including column names, data types, and missing values.
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      7 non-null      int64
 1   Name    7 non-null      object
 2   age     7 non-null      int64
 3   city    7 non-null      object
 4   marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

Step 13 : Display Statistical Summary

In [13]:
# Display summary statistics for all numerical columns.
df_csv.describe()

               Id        age      marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  83.142857
std      2.160247   3.109126   7.267016
min    101.000000  19.000000  70.000000
25%    102.500000  20.000000  80.500000
50%    104.000000  21.000000  84.000000
75%    105.500000  23.000000  87.500000
max    107.000000  28.000000  92.000000

Step 14 : Display Dataset Shape

In [14]:
# Display the number of rows and columns in the DataFrame.
df_csv.shape

(7, 5)

Step 15 : Display column Names

In [15]:
# Display the names of all columns in the DataFrame.
df_csv.columns

Index(['Id', 'Name', 'age', 'city', 'marks'], dtype='object')

Step 16 : Display Data Types

In [16]:
# Display the data type of each column.
df_csv.dtypes

Id        int64
Name     object
age       int64
city     object
marks     int64
dtype: object

Step 17 : Check For Missing Value

In [17]:
# Count the number of missing (null) values in each column.
df_csv.isnull().sum()

Id       0
Name     0
age      0
city     0
marks    0
dtype: int64

Step 18 : Display single Column

In [18]:
# Display only the 'marks' column.
df_csv["marks"]

0    85
1    92
2    70
3    80
4    81
5    84
6    90
Name: marks, dtype: int64

Step 19 : Display multiple column

In [19]:
# Display only the 'Name' and 'marks' columns.
df_csv[["Name","marks"]]

     Name  marks
0   rahul     85
1   priya     92
2    amit     70
3    riya     80
4   karan     81
5  krisha     84
6   harry     90

Step 20 : Display Filter Records

In [20]:
# Display students whose marks are greater than 80.
df_csv[df_csv["marks"]>80]

    Id    Name  age        city  marks
0  101   rahul   20       surat     85
1  102   priya   21     navsari     92
4  105   karan   22       surat     81
5  106  krisha   24      valsad     84
6  107   harry   28  ahemedabad     90

Step 21 : Calculate Average Marks

In [21]:
# Calculate and display the average marks of all students.
df_csv["marks"].mean()

np.float64(83.14285714285714)

Step 22 : Sort Data

In [22]:
# Sort the DataFrame by marks in descending order.
# Students with the highest marks will appear first.
df_csv.sort_values(by="marks",ascending=False)

    Id    Name  age         city  marks
1  102   priya   21      navsari     92
6  107   harry   28   ahemedabad     90
0  101   rahul   20        surat     85
5  106  krisha   24       valsad     84
4  105   karan   22        surat     81
3  104    riya   20  gandhinagar     80
2  103    amit   19      bharuch     70