# **Practical - 2**

####**AIM : Perform data inspection, cleaning, handling missing values, duplicate removal, and data transformation using Pandas.**

Step 1: Import pandas library

In [2]:
## Import pandas so we can work with tables and data
import pandas as pd

Step 2 : Create DataSet

In [3]:
# Store student names, ages, cities, and marks inside a dictionary
data = {
    "ID":[101,102,103,104,104,105,106,107],
    "Name": ["Rahul", "Priya", "Amit", None, "Riya", "Ajay", "Naresh", "Jainil"],
    "Age": [20, 21, None, 20, 20, 22, 23, 28],
    "City": ["Surat", "Navsari", "Surat", "Bharuch", "Bharuch", "Navsari", "Surat", "Ahmedabad"],
    "Marks": [85, None, 78, 88, 88, 81, 90, 93]
}

Step 3 : Create DataFrame

In [4]:
# A DataFrame arranges the data into rows and columns like a table
df=pd.DataFrame(data)
df

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107  Jainil  28.0  Ahmedabad   93.0

step 4 : Display first 5 record

In [5]:
# head() lets us quickly see the first five rows of our dataset
df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

step 5 : Display last 5 record

In [6]:
# tail() is useful when we want to check the records at the bottom(last five rows)
df.tail()

    ID    Name   Age       City  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107  Jainil  28.0  Ahmedabad   93.0

step 6 : Display Information

In [7]:
# info() tells us about columns, data types, and how many values are available
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

step 7 : Display Statistical Summary

In [8]:
# describe() gives useful values such as average, minimum, maximum, and count
df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

Step 8 : Display Dimension of Dataset

In [9]:
# shape tells us how many rows and columns are present
df.shape

(8, 5)

Step 9 : Display Name of column

In [10]:
# columns helps us know which fields are available in our dataset
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step 10 : Display DataType of each column

In [11]:
# dtypes tells us whether a column contains numbers, text, or decimal values
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

Step 11 : Check missing values

In [12]:
# isnull() finds empty cells and sum() counts them for each column df.isnull().sum()
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

Step 12 : Fill missing values in Marks column

In [13]:
# Find the average marks and use it wherever the Marks value is missing
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit   NaN      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107  Jainil  28.0  Ahmedabad  93.000000

Step 13 : Fill missing values in Age column

In [14]:
# Use the average age to replace the empty Age value
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107  Jainil  28.0  Ahmedabad  93.000000

Step 14 : Fill missing values in Name column

In [15]:
# Replace the empty name with "Unknown" so the cell is no longer blank
df["Name"] = df["Name"].fillna("unknown")
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107   Jainil  28.0  Ahmedabad  93.000000

Step 15:Detect Duplicate records

In [16]:
# duplicated() tells us which rows appear more than once
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

Step 16 : Count total no of Duplicate record

In [17]:
# sum() adds all the True values to give us the total number of duplicates
df.duplicated().sum()

np.int64(0)

Step 17 : Remove Duplicate column

In [18]:
# drop_duplicates() keeps one copy and removes repeated rows
df = df.drop_duplicates()
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107   Jainil  28.0  Ahmedabad  93.000000

Step 18 :Rename column Marks to Score

In [19]:
# rename() is used when we want to give a column a new name
df.rename(columns={"Marks": "Score"}, inplace=True)
df

    ID     Name   Age       City      Score
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107   Jainil  28.0  Ahmedabad  93.000000

Step 19 : Convert Age colum Datatype from float to int

In [20]:
# astype(int) converts the Age values into whole numbers
df["Age"] = df["Age"].astype(int)
df.dtypes

ID         int64
Name      object
Age        int64
City      object
Score    float64
dtype: object

Step 20 : Create new column Final score

In [21]:
# Increase the Score by 10% and store the result in a new column
df["Final score"] = df["Score"] + 5
df

    ID     Name  Age       City      Score  Final score
0  101    Rahul   20      Surat  85.000000    90.000000
1  102    Priya   21    Navsari  86.142857    91.142857
2  103     Amit   22      Surat  78.000000    83.000000
3  104  unknown   20    Bharuch  88.000000    93.000000
4  104     Riya   20    Bharuch  88.000000    93.000000
5  105     Ajay   22    Navsari  81.000000    86.000000
6  106   Naresh   23      Surat  90.000000    95.000000
7  107   Jainil   28  Ahmedabad  93.000000    98.000000

Step 21 : Convert all student name to uppercase

In [22]:
# upper() converts names into Upper case
df["Name"] = df["Name"].str.upper()
df

    ID     Name  Age       City      Score  Final score
0  101    RAHUL   20      Surat  85.000000    90.000000
1  102    PRIYA   21    Navsari  86.142857    91.142857
2  103     AMIT   22      Surat  78.000000    83.000000
3  104  UNKNOWN   20    Bharuch  88.000000    93.000000
4  104     RIYA   20    Bharuch  88.000000    93.000000
5  105     AJAY   22    Navsari  81.000000    86.000000
6  106   NARESH   23      Surat  90.000000    95.000000
7  107   JAINIL   28  Ahmedabad  93.000000    98.000000

Step 22 : Convert city name to lowercase

In [23]:
#lower() converts city names such as "Surat" into "surat"
df["City"] = df["City"].str.lower()
df

    ID     Name  Age       City      Score  Final score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107   JAINIL   28  ahmedabad  93.000000    98.000000

Step 23 : Removw leading and trailing whitespace from City column

In [24]:
#Remove extra spaces from the beginning and end of city names
df["City"] = df["City"].str.strip()
df

    ID     Name  Age       City      Score  Final score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107   JAINIL   28  ahmedabad  93.000000    98.000000

Step 24 : Sort data based on Final score in Descending order

In [25]:
# Sort the data by Final Score from highest to lowest
df_sorted = df.sort_values(by="Final score", ascending=False)
# Display the sorted data
df_sorted

    ID     Name  Age       City      Score  Final score
7  107   JAINIL   28  ahmedabad  93.000000    98.000000
6  106   NARESH   23      surat  90.000000    95.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
0  101    RAHUL   20      surat  85.000000    90.000000
5  105     AJAY   22    navsari  81.000000    86.000000
2  103     AMIT   22      surat  78.000000    83.000000

Step 25 : Save cleaned DataFrame as new CSV file.

In [26]:
# Save the cleaned dataset as a CSV file
# index=False prevents pandas from adding an extra index column
df.to_csv("cleaned-students.csv", index=False)
# Show a message after the file is successfully created
print("Dataset Created Successfully")

Dataset Created Successfully