PEN : 240840116024

# **Practical - 3**

####**AIM : Apply ƒiltering, sorting, aggregation, and GroupBy operations on real-world datasets.**

**Step 1 : Import pandas library**

In [1]:
# Import pandas to work with data and tables.
# 'pd' is the short name used for pandas.
import pandas as pd

**Step 2 : create sample dataset**

In [2]:
# Create employee details in a dictionary.
# It contains employee ID, name, department, city, salary, and experience.
data = {

    "Emp_ID":[101,102,103,104,105,106,107,108],
    "Name":["Rahul","PRIYA","Amit","Riya","Karan","Neha","Vivek","Pooja"],
    "Department":["IT","HR","IT","Finance","HR","Finance","IT","HR"],
    "City":["Surat","Navsari","Surat","Valsad","Surat","Navsari","Valsad","Surat"],
    "Salary":[45000,38000,52000,48000,40000,51000,60000,42000],
    "Experience":[2,1,5,4,2,6,8,3]

}

**Step 3 : Create DataFrame**

In [3]:
# Convert the data into a DataFrame.
# A DataFrame stores data in rows and columns.
df=pd.DataFrame(data)
df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  PRIYA         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step 4  : Display the DataSet**

In [4]:
# Display complete DataFrame
df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  PRIYA         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step 5:Filter the Data**

Task 1:Display Employee from IT Department

In [5]:
#Select Employee working in IT Department
df[df["Department"]=="IT"]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Task 2 : Display Employee with salary Greater than 50,000

In [6]:
#Display salary whose salary is greater than 50,000
df[df["Salary"]>50000]

   Emp_ID   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

Task 3 : Display Emplopyees from Surat

In [7]:
# Select employees who live in Surat.
# Only records with Surat as the city are displayed.
df[df["City"]=="Surat"]

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

Task 4 : Apply Multiple Condition

In [8]:
#Display Employee from IT dept
#Display salary greater than 50,000
df[(df["Department"]=="IT") & (df["Salary"]>50000)]

   Emp_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**Step 6 : sorting Data**

Task 1 : Sort salary in ascending order

In [9]:
#sort employee by salary from lowest to highest
df.sort_values(by="Salary")

   Emp_ID   Name Department     City  Salary  Experience
1     102  PRIYA         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

Task 2 : sort salary in desecending order

In [10]:
# sort employee by salary in descending order
df.sort_values(by="Salary",ascending=False)

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  PRIYA         HR  Navsari   38000           1

Task 3 : Sort Department and Salary

In [11]:
#sort by Department
# within each Department sort Salaries in ascending order,Department iN DESCENDING ORDER
df.sort_values(by=["Department","Salary"],ascending =[True,False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  PRIYA         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

**Step 7 : Perform Aggregation**

Task 1 : find total salary

In [12]:
# Add all employee salaries together.
# This gives the total salary of all employees
df["Salary"].sum()

np.int64(376000)

Task 2: count average salary

In [13]:
# Find the average salary of employees.
# This gives the mean salary of the dataset.
df["Salary"].mean()

np.float64(47000.0)

Task 3 : display max salary

In [14]:
# Find the highest salary in the dataset.
# max() returns the largest salary value.
df["Salary"].max()

60000

Task 4 : Display min salary

In [15]:
# Find the lowest salary in the dataset.
# min() returns the smallest salary value.
df["Salary"].min()

38000

Task 5 : count total employees

In [16]:
# Count the number of employees.
# The employee IDs are counted to get the total.
df["Emp_ID"].count()

np.int64(8)

**Step 8 :Perform GroupBY**

Task 1 : Display Average salary department_wise

In [17]:
# Group employees according to their department.
# Find the average salary for each department.
df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

Task 2 : Display Minimum salary department-wise

In [18]:
# Group employees by department.
# Find the lowest salary in each department.
df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

Task 3 : count the Employees Department-Wise

In [19]:
# Group employees by department.
# Count the number of employees in each department.
df.groupby("Department")["Emp_ID"].count()

Department
Finance    2
HR         3
IT         3
Name: Emp_ID, dtype: int64

Task 4 : Total Salary Department-Wise

In [20]:
# Group employees according to their department.
# Find the total salary for each department.
df.groupby("Department")["Salary"].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

Task 5 : Display Maximum Salary Department-Wise

In [21]:
# Group employees by department.
# Find the highest salary in each department.
df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

Task 6 : Display City wise salary

In [22]:
# Group employees according to their city.
# Find the average salary for each city.
df.groupby("City")["Salary"].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

**Step 9 :Multiple Aggregation Function**

Task : Multiple Aggregation by Department

In [23]:
#Apply multiple statistical function
#to the Salary column for each Dapartment
df.groupby("Department")["Salary"].agg(["count","sum","mean","min","max"])

            count     sum          mean    min    max
Department
Finance         2   99000  49500.000000  48000  51000
HR              3  120000  40000.000000  38000  42000
IT              3  157000  52333.333333  45000  60000

**Step 7: Save Result**

In [24]:
#save the dataset into a CSV file
df.to_csv("Employee_Data.csv",index=False)
print("CSV file created successfully!")

CSV file created successfully!

**Download CSV file**

In [25]:
# Save the employee data into a CSV file.
df.to_csv("Employee_Data.csv",index=False)
# Import the files module from Google Colab.
# It allows us to download files to our computer.
from google.colab import files
# Download the created CSV file.
files.download("Employee_Data.csv")